### PR TITLE
Fix to not show column labels for columns which are disabled

### PR DESCRIPTION
**Pull request by lukasinko**

### CODE REVIEW

**Comment by lukasinko** [comment]
@alperenersoy Can i ask you for review ? Thank you.

**Comment by alperenersoy** [comment]
looks unnecessary, probably was there by mistake. thanks for your contribution.

**Comment by lukasinko** [comment]
It was breaking situation when `tableColumnsDisabled` is set. It then doesn't clear the `$columns` array and they are again populated from `$table` columns. With this fix, i can easily do 

```
->disableTableColumns(true)
                    ->withColumns(array_filter($table->getVisibleColumns(), (fn ($column) => $column->getName() === "web.url")))
```
To show only columns i want (via `withColumns` and disabling `disableTableColumns`. 

Thank you for merging it so fast. I will probably have to wait some time for new release to use in my project ?

**Comment by alperenersoy** [comment]
yes probably forgot to delete it after the disable feature.

I've already released it, you don't need to wait.

**Comment by lukasinko** [comment]
Thanks a lot !

**Pull request merged**
